### ISSUE TITLE
Bot goes offline

### ISSUE THREAD

**Issue by Code-ParagonX** [Tomato6966/Musicium#107]
The bot keeps going offline after a couple of hours please help

**Comment by Tomato6966** [comment]
IF you are hosting on Replit.com make sure to add an uptimer system with a little express server so that the repl doesnt go in a sleeping mode (turn off) or consider buying the hacker plan, so you can turn it to the always on state.

If you want a powerful fast VPS check out: https://bero.milrato.dev

**Comment by testbot-github** [comment]
> The bot keeps going offline after a couple of hours please help

Or it might be because of inactivity of ur bot.
Make sure u do somethin to make ur bot do something after like x mins like changing status which will make ur 24/7.

**Comment by Random-1s** [comment]
Well I did the always on but it always keeps going off anyway

**Comment by Random-1s** [comment]
> IF you are hosting on Replit.com make sure to add an uptimer system with a little express server so that the repl doesnt go in a sleeping mode (turn off) or consider buying the hacker plan, so you can turn it to the always on state.
> 
> If you want a powerful fast VPS check out: https://bero.milrato.dev

It keeps going off even with always on.
